esphome:
  name: bluetooth-proxy
  friendly_name: bluetooth-proxy
  #name_add_mac_suffix: true
  project:
    name: esphome.bluetooth-proxy
    version: "1.0"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

wifi:
  ssid: "Lovenet IOT"
  password: "Portland"
  domain: ".thesteamedcrab.com"
  fast_connect: true

# Enable Home Assistant API
api:

ota:

#captive_portal:

improv_serial:

dashboard_import:
  package_import_url: github://esphome/firmware/bluetooth-proxy/esp32-generic.yaml@main

esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: true
    #interval: 1100ms
    #window: 1100ms

bluetooth_proxy:
  active: true

#web_server:
#  port: 80

#button:
#  - platform: safe_mode
#    name: Safe Mode Boot
#    entity_category: diagnostic